'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RTO.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1363933683_494576713_1_pictures_of_rto_consultants_in_bangalore_9060059444_9060084008_karnataka_rto_agents_in_bangalore_ma() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1363933683_494576713_1-pictures-of-rto-consultants-in-bangalore-9060059444-906008"& _ 
                        "4008-karnataka-rto-agents-in-bangalore-ma", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1423854() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1423854", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3869354719_6131325967_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3869354719_6131325967_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3869354719_6131325967_o1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3869354719_6131325967_o1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _518079_background_hd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("518079-background-hd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _518079_background_hd1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("518079-background-hd1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property background_wallpapers_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background-wallpapers-26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bajaj_Pulsar_RS_200_projector_headlamps_1024x526() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bajaj-Pulsar-RS-200-projector-headlamps-1024x526", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BANGALORE1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BANGALORE1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Beautiful_green_fresh_desktop_wallpaper_1366x768() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Beautiful-green-fresh-desktop-wallpaper-1366x768", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property black_minimalistic_dark_patterns_textures_1366x768() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("black_minimalistic_dark_patterns_textures_1366x768", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blue_pattern_background_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue-pattern-background-1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blue_pattern_background_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue-pattern-background-11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Blue_Plastic_wallpaper_1366x768() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Blue_Plastic_wallpaper_1366x768", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blue_waves_1366x768_abstract_background_93_258598435() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue-waves-1366x768-abstract-background-93-258598435", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cartoon_directional_sign_wood_clip_art_22873215() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cartoon_directional_sign_wood_clip_art_22873215", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Chennai_road_map() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chennai road map", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property codigo_cvv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("codigo-cvv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dealer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dealer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dealer1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dealer1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Drivers_license_application_copy__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Drivers license application copy (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property driving_license_640x360() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("driving-license-640x360", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ducati_999_2005_01_b1920() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ducati_999_2005_01_b1920", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property green_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("green-02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property india_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("india-5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property india_51() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("india-51", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property light_line_surface_texture_15641_1366x768() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("light_line_surface_texture_15641_1366x768", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lOGP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lOGP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property maxresdefault() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("maxresdefault", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NEw_Delhi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NEw Delhi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pulsar_200_SS_rear_rendering() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pulsar-200-SS-rear-rendering", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Q112() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Q112", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Q12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Q12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Q13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Q13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Q17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Q17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Q19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Q19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Q29() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Q29", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RTO_National_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RTO_National_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Seal_of_Karnataka() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Seal_of_Karnataka", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Three_Differant_Indian_Chief_Bike_On_Road_Full_HD_Wallpapers_1024x576() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Three-Differant-Indian-Chief-Bike-On-Road-Full-HD-Wallpapers-1024x576", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Vidhana_Soudha_2012() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vidhana_Soudha_2012", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Vidhana_Soudha_20121() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vidhana_Soudha_20121", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ws_Black_Denim_Background_1366x768() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ws_Black_Denim_Background_1366x768", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
